import localFont from "next/font/local";
import "./globals.css";

import Link from "next/link";
import Navigation from "@/components/Navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navigation />
        {/* <header className="bg-slate-500 text-white text-center p-4">
          <nav>
            <ul className="flex justify-center gap-10">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/produkter">Produkter</Link>
              </li>
              <li>
                <Link href="/kontakt">Kontakt</Link>
              </li>
              <li>
                <Link href="/kontakt/copenhagen">Kontakt Copenhagen</Link>
              </li>
            </ul>
          </nav>
        </header> */}
        {/* her er children og er f.eks. page.js */}
        {children}
      </body>
    </html>
  );
}
